---
 - hosts: db01
   become: true
   tasks:
    - name: install mysql-server
      apt: name=mysql-server state=present update_cache=yes

    - name: ensure my-sql service starte
      service: name=mysql state=started enabled=yes
