---
 - name: stop service in lb
   hosts: loadbalancer
   become: yes

   tasks:
     - name: stop loadbalancer
       service: name=nginx state=stopped

 - name: stop service in webserver
   hosts: webservers
   become: yes

   tasks:
     - name: stop webserver
       service: name=apache2 state=stopped

 - name: restart service in db
   hosts: database
   become: yes

   tasks:
     - name: restart db
       service: name=mysql state=restarted

 - name: start webserver
   hosts: webservers
   become: yes

   tasks:
     - name: start web servers
       service: name=apache2 state=started

 - name: start load balancer
   hosts: loadbalancer
   become: yes

   tasks:
     - name: start load balancer
       service: name=nginx state=started
